name: Inspektor Gadget Release
on:
  release:
    types: [published]

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Update new version in krew-index
      if: github.repository == 'inspektor-gadget/inspektor-gadget'
      uses: rajatjindal/krew-release-bot@df3eb197549e3568be8b4767eec31c5e8e8e6ad8 # v0.0.46
      with:
        workdir: /home/runner/work/inspektor-gadget/inspektor-gadget
        krew_template_file: .krew.yaml
    - name: Update version in various files
      id: bump_gadgets
      if: github.repository == 'inspektor-gadget/inspektor-gadget'
      run: |
        # Get the version without the "v" prefix
        inspektor_gadget_version=$(echo $GITHUB_REF_NAME | tr -d '"v')

        echo "version=${inspektor_gadget_version}" >> $GITHUB_OUTPUT

        DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        for PKGFILE in $(find gadgets/ -name artifacthub-pkg.yml) ; do
            # - The 'createdAt' field identifies the release date. It should not
            #   be changed in between releases.
            # - The 'digest' field is modified to request reindexing from
            #   artifacthub. It is fine to modify it more often.
            sed -i \
                -e "s/^version:.*$/version: ${inspektor_gadget_version}/" \
                -e "s/^createdAt:.*$/createdAt: \"${DATE}\"/" \
                -e "s/^digest:.*$/digest: \"${DATE}\"/" \
                $PKGFILE
        done

        # Update links to release assets
        sed -i "s|\([-/]\)v[0-9]\.[0-9]*\.[0-9]*|\1v${inspektor_gadget_version}|g" README.md

        # The following is to support multiline with GITHUB_OUTPUT, see:
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        echo "changes<<EOF" >> $GITHUB_OUTPUT
        echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Create PR
      if: ${{ steps.bump_gadgets.outputs.changes != '' }}
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Post-release: update version to v${{ steps.bump_gadgets.outputs.version }}'
        branch: 'auto_bump_gadgets_v${{ steps.bump_gadgets.outputs.version }}'
        base: main
        delete-branch: true
        title: 'Post-release: update version to v${{ steps.bump_gadgets.outputs.version }}'
        body: |
          Hi.

          We released a new version of Inspektor Gadget [v${{ steps.bump_gadgets.outputs.version }}](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.bump_gadgets.outputs.version }}), so the [official gadgets on Artifact Hub](https://artifacthub.io/packages/search?repo=gadgets) needs to be updated.

          This PR was automatically generated by a CI job:
          * [update-inspektor-gadget-release.yaml](https://github.com/${{ github.repository }}/blob/main/.github/workflows/release.yml)

          This PR will not be automatically merged. Please review, edit and merge as appropriate.

          Checklist:
          - [ ] Check that the [Inspektor Gadget CI](https://github.com/${{ github.repository }}/actions/workflows/inspektor-gadget.yml) completed successfully.
          - [ ] Check that the gadgets OCI images have a new tag with the correct version (v${{ steps.bump_gadgets.outputs.version }}). For example, [gadget/trace_open](https://github.com/${{ github.repository }}/pkgs/container/gadget%2Ftrace_open).
          - [ ] Check the diff of this PR.

          After merging, the Artifact Hub bot will notice the update. It might take 30 minutes.
          Then, the following will be updated:
          https://artifacthub.io/packages/search?repo=gadgets

          In case of problems, please check the logs in the [Artifact Hub control panel](https://artifacthub.io/control-panel).

          Best regards.
